---
- name: Database Backup
  hosts: test-server
  become: True
  gather_facts: True
  tasks:
  - name: Create Backup Directory
    file:
      path: ~/databases/
      state: directory
  - name: Dump Databases
    mysql_db:
      state: dump
      name: all
      target: ~/databases/{{ ansible_date_time.date }}.sql
      login_user: root
      login_password: password
  - name: Archive Database Dump
    archive:
      path: ~/databases/*.sql
      dest: ~/databases/{{ ansible_date_time.date }}.tar.gz
      remove: yes
  - name: Fetch Backup From The Server
    synchronize:
      mode: pull
      src: "~/databases/"
      dest: "~/backup/"
      rsync_opts: "--remove-source-files"
...
