---
- name: Database Backup
  hosts: test-server
  become: True
  gather_facts: True
  tasks:
  - name: Create Backup Directory
    file:
      path: /var/www/html/databases/
      state: directory
  - name: Dump Databases
    mysql_db:
      state: dump
      name: all
      target: /var/www/html/databases/{{ ansible_date_time.date }}.sql
      login_user: root
      login_password: password
  - name: Archive Database Dump
    archive:
      path: /var/www/html/databases/*.sql
      dest: /var/www/html/databases/{{ ansible_date_time.date }}.tar.gz
      remove: yes
  - name: Fetch Backup From The Server
    synchronize:
      mode: pull
      src: "/var/www/html/databases/"
      dest: "~/backup/"
      rsync_opts: "--remove-source-files
...
